# Generated by Django 2.2 on 2020-02-04 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundlookup', '0002_auto_20190818_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_type', models.CharField(choices=[('PB', 'Publicity'), ('EV', 'Event'), ('TR', 'Travel'), ('MC', 'Miscellaneous')], default='MC', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('VR', 'Vendor'), ('FD', 'Funder'), ('PP', 'Political Party'), ('AD', 'Admin')], default='FD', max_length=2)),
                ('avatar_path', models.CharField(max_length=500, verbose_name='Avatar Path')),
                ('metamask_address', models.CharField(max_length=500, verbose_name='Metamask Address')),
                ('available_funds', models.FloatField(verbose_name='Available Funds')),
                ('amount_requested', models.FloatField(verbose_name='Amount Requested')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_donated_by', to=settings.AUTH_USER_MODEL)),
                ('donated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_donated_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Funder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funder_type', models.CharField(choices=[('IND', 'Individual'), ('ORG', 'Organisation')], default='IND', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
