# Generated by Django 2.2 on 2020-02-06 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundlookup', '0004_politicalparty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('donated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_donated_by', to=settings.AUTH_USER_MODEL)),
                ('donated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_donated_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
