# Generated by Django 2.2.6 on 2020-02-06 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundlookup', '0005_auto_20200206_1227'),
        ('fundlookup', '0005_userprofile_user_location'),
    ]

    operations = [
    ]
