# Generated by Django 2.2 on 2020-02-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundlookup', '0006_merge_20200206_2116'),
        ('fundlookup', '0006_auto_20200207_0509'),
    ]

    operations = [
    ]
