# Generated by Django 2.2 on 2020-02-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundlookup', '0007_merge_20200207_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_location',
        ),
    ]
